version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    command: npm start
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meetingsdb

volumes:
  postgres_data: # Volume to persist database data
